spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invenza_db
    username: postgres
    password: Rishi@712
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5000
  error:
    include-message: always


